import { View, Text, ScrollView, Image, StyleSheet, Pressable, FlatList } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { AntDesign } from "@expo/vector-icons";

// import gambar from "../assets/images/react-logo@3x.png";

// const gambar = require("../assets/images/react-logo@3x.png");
const gambar = require("@/assets/images/react-logo.png");

const data = {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 7,
    gaps: "no",
    preparationMinutes: 20,
    cookingMinutes: 65,
    aggregateLikes: 1,
    healthScore: 23,
    creditsText: "Foodnetwork",
    sourceName: "Foodnetwork",
    pricePerServing: 496.27,
    extendedIngredients: [
        {
            id: 11215,
            aisle: "Produce",
            image: "garlic.png",
            consistency: "SOLID",
            name: "garlic",
            nameClean: "garlic",
            original: "1/4 cup minced garlic",
            originalName: "minced garlic",
            amount: 0.25,
            unit: "cup",
            meta: ["minced"],
            measures: {
                us: {
                    amount: 0.25,
                    unitShort: "cups",
                    unitLong: "cups",
                },
                metric: {
                    amount: 34.0,
                    unitShort: "ml",
                    unitLong: "milliliters",
                },
            },
        },
        {
            id: 11216,
            aisle: "Produce",
            image: "ginger.png",
            consistency: "SOLID",
            name: "ginger",
            nameClean: "ginger",
            original: "2 tablespoons grated ginger",
            originalName: "grated ginger",
            amount: 2.0,
            unit: "tablespoons",
            meta: ["grated"],
            measures: {
                us: {
                    amount: 2.0,
                    unitShort: "Tbsps",
                    unitLong: "Tbsps",
                },
                metric: {
                    amount: 2.0,
                    unitShort: "Tbsps",
                    unitLong: "Tbsps",
                },
            },
        },
        {
            id: 9160,
            aisle: "Produce",
            image: "lime-juice.png",
            consistency: "LIQUID",
            name: "lime juice",
            nameClean: "lime juice",
            original: "2 cups fresh lime juice",
            originalName: "fresh lime juice",
            amount: 2.0,
            unit: "cups",
            meta: ["fresh"],
            measures: {
                us: {
                    amount: 2.0,
                    unitShort: "cups",
                    unitLong: "cups",
                },
                metric: {
                    amount: 484.0,
                    unitShort: "ml",
                    unitLong: "milliliters",
                },
            },
        },
        {
            id: 10015004,
            aisle: "Seafood",
            image: "fish-fillet.png",
            consistency: "SOLID",
            name: "sea bass fillets",
            nameClean: "seabass fillets",
            original: "6 (5-ounce) sea bass fillets",
            originalName: "sea bass fillets",
            amount: 30.0,
            unit: "ounce",
            meta: [],
            measures: {
                us: {
                    amount: 30.0,
                    unitShort: "oz",
                    unitLong: "ounces",
                },
                metric: {
                    amount: 850.486,
                    unitShort: "g",
                    unitLong: "grams",
                },
            },
        },
        {
            id: 4058,
            aisle: "Ethnic Foods",
            image: "sesame-oil.png",
            consistency: "LIQUID",
            name: "sesame oil",
            nameClean: "sesame oil",
            original: "1/4 cup sesame oil",
            originalName: "sesame oil",
            amount: 0.25,
            unit: "cup",
            meta: [],
            measures: {
                us: {
                    amount: 0.25,
                    unitShort: "cups",
                    unitLong: "cups",
                },
                metric: {
                    amount: 54.5,
                    unitShort: "ml",
                    unitLong: "milliliters",
                },
            },
        },
        {
            id: 19335,
            aisle: "Baking",
            image: "sugar-in-bowl.png",
            consistency: "SOLID",
            name: "sugar",
            nameClean: "sugar",
            original: "1/4 cup sugar",
            originalName: "sugar",
            amount: 0.25,
            unit: "cup",
            meta: [],
            measures: {
                us: {
                    amount: 0.25,
                    unitShort: "cups",
                    unitLong: "cups",
                },
                metric: {
                    amount: 50.0,
                    unitShort: "g",
                    unitLong: "grams",
                },
            },
        },
        {
            id: 11670,
            aisle: "Produce",
            image: "thai-chiles.jpg",
            consistency: "SOLID",
            name: "thai bird chiles",
            nameClean: "thai chili",
            original: "1/2 cup Thai bird chiles, seeded and minced",
            originalName: "Thai bird chiles, seeded and minced",
            amount: 0.5,
            unit: "cup",
            meta: ["minced", "seeded"],
            measures: {
                us: {
                    amount: 0.5,
                    unitShort: "cups",
                    unitLong: "cups",
                },
                metric: {
                    amount: 75.0,
                    unitShort: "g",
                    unitLong: "grams",
                },
            },
        },
        {
            id: 1006179,
            aisle: "Ethnic Foods",
            image: "asian-fish-sauce.jpg",
            consistency: "LIQUID",
            name: "thai fish sauce",
            nameClean: "thai fish sauce",
            original: "1/2 cup Thai fish sauce",
            originalName: "Thai fish sauce",
            amount: 0.5,
            unit: "cup",
            meta: [],
            measures: {
                us: {
                    amount: 0.5,
                    unitShort: "cups",
                    unitLong: "cups",
                },
                metric: {
                    amount: 116.0,
                    unitShort: "ml",
                    unitLong: "milliliters",
                },
            },
        },
    ],
    id: 1234,
    title: "Grilled Sea Bass with Thai Chili Sauce",
    readyInMinutes: 85,
    servings: 6,
    sourceUrl:
        "http://www.foodnetwork.com/recipes/grilled-sea-bass-with-thai-chili-sauce-recipe/index.html",
    image: "https://img.spoonacular.com/recipes/1234-556x370.jpeg",
    imageType: "jpeg",
    nutrition: {
        nutrients: [
            {
                name: "Calories",
                amount: 292.12,
                unit: "kcal",
                percentOfDailyNeeds: 14.61,
            },
            {
                name: "Fat",
                amount: 12.54,
                unit: "g",
                percentOfDailyNeeds: 19.3,
            },
            {
                name: "Saturated Fat",
                amount: 2.03,
                unit: "g",
                percentOfDailyNeeds: 12.67,
            },
            {
                name: "Carbohydrates",
                amount: 19.27,
                unit: "g",
                percentOfDailyNeeds: 6.42,
            },
            {
                name: "Net Carbohydrates",
                amount: 18.59,
                unit: "g",
                percentOfDailyNeeds: 6.76,
            },
            {
                name: "Sugar",
                amount: 11.12,
                unit: "g",
                percentOfDailyNeeds: 12.35,
            },
            {
                name: "Cholesterol",
                amount: 113.4,
                unit: "mg",
                percentOfDailyNeeds: 37.8,
            },
            {
                name: "Sodium",
                amount: 1619.31,
                unit: "mg",
                percentOfDailyNeeds: 70.4,
            },
            {
                name: "Alcohol",
                amount: 0.0,
                unit: "g",
                percentOfDailyNeeds: 100.0,
            },
            {
                name: "Alcohol %",
                amount: 0.0,
                unit: "%",
                percentOfDailyNeeds: 100.0,
            },
            {
                name: "Protein",
                amount: 27.1,
                unit: "g",
                percentOfDailyNeeds: 54.2,
            },
            {
                name: "Vitamin B12",
                amount: 5.51,
                unit: "µg",
                percentOfDailyNeeds: 91.79,
            },
            {
                name: "Selenium",
                amount: 54.51,
                unit: "µg",
                percentOfDailyNeeds: 77.87,
            },
            {
                name: "Vitamin C",
                amount: 56.49,
                unit: "mg",
                percentOfDailyNeeds: 68.48,
            },
            {
                name: "Vitamin B6",
                amount: 0.64,
                unit: "mg",
                percentOfDailyNeeds: 32.06,
            },
            {
                name: "Phosphorus",
                amount: 308.52,
                unit: "mg",
                percentOfDailyNeeds: 30.85,
            },
            {
                name: "Magnesium",
                amount: 102.53,
                unit: "mg",
                percentOfDailyNeeds: 25.63,
            },
            {
                name: "Vitamin B3",
                amount: 3.71,
                unit: "mg",
                percentOfDailyNeeds: 18.57,
            },
            {
                name: "Potassium",
                amount: 588.01,
                unit: "mg",
                percentOfDailyNeeds: 16.8,
            },
            {
                name: "Vitamin B1",
                amount: 0.19,
                unit: "mg",
                percentOfDailyNeeds: 12.49,
            },
            {
                name: "Vitamin B5",
                amount: 1.23,
                unit: "mg",
                percentOfDailyNeeds: 12.31,
            },
            {
                name: "Manganese",
                amount: 0.21,
                unit: "mg",
                percentOfDailyNeeds: 10.54,
            },
            {
                name: "Iron",
                amount: 1.68,
                unit: "mg",
                percentOfDailyNeeds: 9.33,
            },
            {
                name: "Folate",
                amount: 33.99,
                unit: "µg",
                percentOfDailyNeeds: 8.5,
            },
            {
                name: "Vitamin A",
                amount: 318.11,
                unit: "IU",
                percentOfDailyNeeds: 6.36,
            },
            {
                name: "Copper",
                amount: 0.12,
                unit: "mg",
                percentOfDailyNeeds: 6.0,
            },
            {
                name: "Calcium",
                amount: 53.83,
                unit: "mg",
                percentOfDailyNeeds: 5.38,
            },
            {
                name: "Zinc",
                amount: 0.78,
                unit: "mg",
                percentOfDailyNeeds: 5.21,
            },
            {
                name: "Vitamin B2",
                amount: 0.09,
                unit: "mg",
                percentOfDailyNeeds: 5.03,
            },
            {
                name: "Vitamin K",
                amount: 3.61,
                unit: "µg",
                percentOfDailyNeeds: 3.43,
            },
            {
                name: "Fiber",
                amount: 0.68,
                unit: "g",
                percentOfDailyNeeds: 2.7,
            },
            {
                name: "Vitamin E",
                amount: 0.4,
                unit: "mg",
                percentOfDailyNeeds: 2.68,
            },
        ],
        properties: [
            {
                name: "Glycemic Index",
                amount: 19.18,
                unit: "",
            },
            {
                name: "Glycemic Load",
                amount: 6.4,
                unit: "",
            },
            {
                name: "Inflammation Score",
                amount: -7.0,
                unit: "",
            },
            {
                name: "Nutrition Score",
                amount: 19.652609026950337,
                unit: "%",
            },
        ],
        flavonoids: [
            {
                name: "Cyanidin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Petunidin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Delphinidin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Malvidin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Pelargonidin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Peonidin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Catechin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Epigallocatechin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Epicatechin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Epicatechin 3-gallate",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Epigallocatechin 3-gallate",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Theaflavin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Thearubigins",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Eriodictyol",
                amount: 1.77,
                unit: "mg",
            },
            {
                name: "Hesperetin",
                amount: 7.24,
                unit: "mg",
            },
            {
                name: "Naringenin",
                amount: 0.31,
                unit: "mg",
            },
            {
                name: "Apigenin",
                amount: 0.17,
                unit: "mg",
            },
            {
                name: "Luteolin",
                amount: 0.48,
                unit: "mg",
            },
            {
                name: "Isorhamnetin",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Kaempferol",
                amount: 0.01,
                unit: "mg",
            },
            {
                name: "Myricetin",
                amount: 0.24,
                unit: "mg",
            },
            {
                name: "Quercetin",
                amount: 2.35,
                unit: "mg",
            },
            {
                name: "Theaflavin-3,3'-digallate",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Theaflavin-3'-gallate",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Theaflavin-3-gallate",
                amount: 0.0,
                unit: "",
            },
            {
                name: "Gallocatechin",
                amount: 0.0,
                unit: "",
            },
        ],
        ingredients: [
            {
                id: 11215,
                name: "garlic",
                amount: 0.04,
                unit: "cup",
                nutrients: [
                    {
                        name: "Potassium",
                        amount: 22.72,
                        unit: "mg",
                        percentOfDailyNeeds: 16.8,
                    },
                    {
                        name: "Manganese",
                        amount: 0.09,
                        unit: "mg",
                        percentOfDailyNeeds: 10.54,
                    },
                    {
                        name: "Carbohydrates",
                        amount: 1.88,
                        unit: "g",
                        percentOfDailyNeeds: 6.42,
                    },
                    {
                        name: "Calories",
                        amount: 8.44,
                        unit: "kcal",
                        percentOfDailyNeeds: 14.61,
                    },
                    {
                        name: "Mono Unsaturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B12",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 91.79,
                    },
                    {
                        name: "Magnesium",
                        amount: 1.42,
                        unit: "mg",
                        percentOfDailyNeeds: 25.63,
                    },
                    {
                        name: "Cholesterol",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 37.8,
                    },
                    {
                        name: "Vitamin E",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 2.68,
                    },
                    {
                        name: "Poly Unsaturated Fat",
                        amount: 0.01,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Folic Acid",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B6",
                        amount: 0.07,
                        unit: "mg",
                        percentOfDailyNeeds: 32.06,
                    },
                    {
                        name: "Vitamin B1",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 12.49,
                    },
                    {
                        name: "Vitamin B2",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 5.03,
                    },
                    {
                        name: "Selenium",
                        amount: 0.8,
                        unit: "µg",
                        percentOfDailyNeeds: 77.87,
                    },
                    {
                        name: "Net Carbohydrates",
                        amount: 1.76,
                        unit: "g",
                        percentOfDailyNeeds: 6.76,
                    },
                    {
                        name: "Choline",
                        amount: 1.31,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Calcium",
                        amount: 10.26,
                        unit: "mg",
                        percentOfDailyNeeds: 5.38,
                    },
                    {
                        name: "Vitamin D",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Zinc",
                        amount: 0.07,
                        unit: "mg",
                        percentOfDailyNeeds: 5.21,
                    },
                    {
                        name: "Vitamin A",
                        amount: 0.51,
                        unit: "IU",
                        percentOfDailyNeeds: 6.36,
                    },
                    {
                        name: "Caffeine",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Iron",
                        amount: 0.1,
                        unit: "mg",
                        percentOfDailyNeeds: 9.33,
                    },
                    {
                        name: "Fiber",
                        amount: 0.12,
                        unit: "g",
                        percentOfDailyNeeds: 2.7,
                    },
                    {
                        name: "Saturated Fat",
                        amount: 0.01,
                        unit: "g",
                        percentOfDailyNeeds: 12.67,
                    },
                    {
                        name: "Vitamin B5",
                        amount: 0.03,
                        unit: "mg",
                        percentOfDailyNeeds: 12.31,
                    },
                    {
                        name: "Protein",
                        amount: 0.36,
                        unit: "g",
                        percentOfDailyNeeds: 54.2,
                    },
                    {
                        name: "Alcohol",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 100.0,
                    },
                    {
                        name: "Lycopene",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin C",
                        amount: 1.77,
                        unit: "mg",
                        percentOfDailyNeeds: 68.48,
                    },
                    {
                        name: "Sugar",
                        amount: 0.06,
                        unit: "g",
                        percentOfDailyNeeds: 12.35,
                    },
                    {
                        name: "Fat",
                        amount: 0.03,
                        unit: "g",
                        percentOfDailyNeeds: 19.3,
                    },
                    {
                        name: "Phosphorus",
                        amount: 8.67,
                        unit: "mg",
                        percentOfDailyNeeds: 30.85,
                    },
                    {
                        name: "Folate",
                        amount: 0.17,
                        unit: "µg",
                        percentOfDailyNeeds: 8.5,
                    },
                    {
                        name: "Vitamin B3",
                        amount: 0.04,
                        unit: "mg",
                        percentOfDailyNeeds: 18.57,
                    },
                    {
                        name: "Copper",
                        amount: 0.02,
                        unit: "mg",
                        percentOfDailyNeeds: 6.0,
                    },
                    {
                        name: "Vitamin K",
                        amount: 0.1,
                        unit: "µg",
                        percentOfDailyNeeds: 3.43,
                    },
                    {
                        name: "Sodium",
                        amount: 0.96,
                        unit: "mg",
                        percentOfDailyNeeds: 70.4,
                    },
                ],
            },
            {
                id: 11216,
                name: "ginger",
                amount: 0.33,
                unit: "tablespoons",
                nutrients: [
                    {
                        name: "Potassium",
                        amount: 9.68,
                        unit: "mg",
                        percentOfDailyNeeds: 16.8,
                    },
                    {
                        name: "Manganese",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 10.54,
                    },
                    {
                        name: "Carbohydrates",
                        amount: 0.41,
                        unit: "g",
                        percentOfDailyNeeds: 6.42,
                    },
                    {
                        name: "Calories",
                        amount: 1.87,
                        unit: "kcal",
                        percentOfDailyNeeds: 14.61,
                    },
                    {
                        name: "Mono Unsaturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B12",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 91.79,
                    },
                    {
                        name: "Magnesium",
                        amount: 1.0,
                        unit: "mg",
                        percentOfDailyNeeds: 25.63,
                    },
                    {
                        name: "Cholesterol",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 37.8,
                    },
                    {
                        name: "Vitamin E",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 2.68,
                    },
                    {
                        name: "Poly Unsaturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Folic Acid",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B6",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 32.06,
                    },
                    {
                        name: "Vitamin B1",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 12.49,
                    },
                    {
                        name: "Vitamin B2",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 5.03,
                    },
                    {
                        name: "Selenium",
                        amount: 0.02,
                        unit: "µg",
                        percentOfDailyNeeds: 77.87,
                    },
                    {
                        name: "Net Carbohydrates",
                        amount: 0.37,
                        unit: "g",
                        percentOfDailyNeeds: 6.76,
                    },
                    {
                        name: "Choline",
                        amount: 0.67,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Calcium",
                        amount: 0.37,
                        unit: "mg",
                        percentOfDailyNeeds: 5.38,
                    },
                    {
                        name: "Vitamin D",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Zinc",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 5.21,
                    },
                    {
                        name: "Vitamin A",
                        amount: 0.0,
                        unit: "IU",
                        percentOfDailyNeeds: 6.36,
                    },
                    {
                        name: "Caffeine",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Iron",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 9.33,
                    },
                    {
                        name: "Fiber",
                        amount: 0.05,
                        unit: "g",
                        percentOfDailyNeeds: 2.7,
                    },
                    {
                        name: "Saturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 12.67,
                    },
                    {
                        name: "Vitamin B5",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 12.31,
                    },
                    {
                        name: "Protein",
                        amount: 0.04,
                        unit: "g",
                        percentOfDailyNeeds: 54.2,
                    },
                    {
                        name: "Alcohol",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 100.0,
                    },
                    {
                        name: "Lycopene",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin C",
                        amount: 0.12,
                        unit: "mg",
                        percentOfDailyNeeds: 68.48,
                    },
                    {
                        name: "Sugar",
                        amount: 0.04,
                        unit: "g",
                        percentOfDailyNeeds: 12.35,
                    },
                    {
                        name: "Fat",
                        amount: 0.02,
                        unit: "g",
                        percentOfDailyNeeds: 19.3,
                    },
                    {
                        name: "Phosphorus",
                        amount: 0.79,
                        unit: "mg",
                        percentOfDailyNeeds: 30.85,
                    },
                    {
                        name: "Folate",
                        amount: 0.26,
                        unit: "µg",
                        percentOfDailyNeeds: 8.5,
                    },
                    {
                        name: "Vitamin B3",
                        amount: 0.02,
                        unit: "mg",
                        percentOfDailyNeeds: 18.57,
                    },
                    {
                        name: "Copper",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 6.0,
                    },
                    {
                        name: "Vitamin K",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 3.43,
                    },
                    {
                        name: "Sodium",
                        amount: 0.3,
                        unit: "mg",
                        percentOfDailyNeeds: 70.4,
                    },
                ],
            },
            {
                id: 9160,
                name: "lime juice",
                amount: 0.33,
                unit: "cups",
                nutrients: [
                    {
                        name: "Potassium",
                        amount: 94.38,
                        unit: "mg",
                        percentOfDailyNeeds: 16.8,
                    },
                    {
                        name: "Manganese",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 10.54,
                    },
                    {
                        name: "Carbohydrates",
                        amount: 6.79,
                        unit: "g",
                        percentOfDailyNeeds: 6.42,
                    },
                    {
                        name: "Calories",
                        amount: 20.17,
                        unit: "kcal",
                        percentOfDailyNeeds: 14.61,
                    },
                    {
                        name: "Mono Unsaturated Fat",
                        amount: 0.01,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B12",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 91.79,
                    },
                    {
                        name: "Magnesium",
                        amount: 6.45,
                        unit: "mg",
                        percentOfDailyNeeds: 25.63,
                    },
                    {
                        name: "Cholesterol",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 37.8,
                    },
                    {
                        name: "Vitamin E",
                        amount: 0.18,
                        unit: "mg",
                        percentOfDailyNeeds: 2.68,
                    },
                    {
                        name: "Poly Unsaturated Fat",
                        amount: 0.02,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Folic Acid",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B6",
                        amount: 0.03,
                        unit: "mg",
                        percentOfDailyNeeds: 32.06,
                    },
                    {
                        name: "Vitamin B1",
                        amount: 0.02,
                        unit: "mg",
                        percentOfDailyNeeds: 12.49,
                    },
                    {
                        name: "Vitamin B2",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 5.03,
                    },
                    {
                        name: "Selenium",
                        amount: 0.08,
                        unit: "µg",
                        percentOfDailyNeeds: 77.87,
                    },
                    {
                        name: "Net Carbohydrates",
                        amount: 6.47,
                        unit: "g",
                        percentOfDailyNeeds: 6.76,
                    },
                    {
                        name: "Choline",
                        amount: 4.11,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Calcium",
                        amount: 11.29,
                        unit: "mg",
                        percentOfDailyNeeds: 5.38,
                    },
                    {
                        name: "Vitamin D",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Zinc",
                        amount: 0.06,
                        unit: "mg",
                        percentOfDailyNeeds: 5.21,
                    },
                    {
                        name: "Vitamin A",
                        amount: 40.33,
                        unit: "IU",
                        percentOfDailyNeeds: 6.36,
                    },
                    {
                        name: "Caffeine",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Iron",
                        amount: 0.07,
                        unit: "mg",
                        percentOfDailyNeeds: 9.33,
                    },
                    {
                        name: "Fiber",
                        amount: 0.32,
                        unit: "g",
                        percentOfDailyNeeds: 2.7,
                    },
                    {
                        name: "Saturated Fat",
                        amount: 0.01,
                        unit: "g",
                        percentOfDailyNeeds: 12.67,
                    },
                    {
                        name: "Vitamin B5",
                        amount: 0.1,
                        unit: "mg",
                        percentOfDailyNeeds: 12.31,
                    },
                    {
                        name: "Protein",
                        amount: 0.34,
                        unit: "g",
                        percentOfDailyNeeds: 54.2,
                    },
                    {
                        name: "Alcohol",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 100.0,
                    },
                    {
                        name: "Lycopene",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin C",
                        amount: 24.2,
                        unit: "mg",
                        percentOfDailyNeeds: 68.48,
                    },
                    {
                        name: "Sugar",
                        amount: 1.36,
                        unit: "g",
                        percentOfDailyNeeds: 12.35,
                    },
                    {
                        name: "Fat",
                        amount: 0.06,
                        unit: "g",
                        percentOfDailyNeeds: 19.3,
                    },
                    {
                        name: "Phosphorus",
                        amount: 11.29,
                        unit: "mg",
                        percentOfDailyNeeds: 30.85,
                    },
                    {
                        name: "Folate",
                        amount: 8.07,
                        unit: "µg",
                        percentOfDailyNeeds: 8.5,
                    },
                    {
                        name: "Vitamin B3",
                        amount: 0.11,
                        unit: "mg",
                        percentOfDailyNeeds: 18.57,
                    },
                    {
                        name: "Copper",
                        amount: 0.02,
                        unit: "mg",
                        percentOfDailyNeeds: 6.0,
                    },
                    {
                        name: "Vitamin K",
                        amount: 0.48,
                        unit: "µg",
                        percentOfDailyNeeds: 3.43,
                    },
                    {
                        name: "Sodium",
                        amount: 1.61,
                        unit: "mg",
                        percentOfDailyNeeds: 70.4,
                    },
                ],
            },
            {
                id: 10015004,
                name: "sea bass fillets",
                amount: 5.0,
                unit: "ounce",
                nutrients: [
                    {
                        name: "Manganese",
                        amount: 0.02,
                        unit: "mg",
                        percentOfDailyNeeds: 10.54,
                    },
                    {
                        name: "Potassium",
                        amount: 362.87,
                        unit: "mg",
                        percentOfDailyNeeds: 16.8,
                    },
                    {
                        name: "Carbohydrates",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 6.42,
                    },
                    {
                        name: "Calories",
                        amount: 137.5,
                        unit: "kcal",
                        percentOfDailyNeeds: 14.61,
                    },
                    {
                        name: "Mono Unsaturated Fat",
                        amount: 0.94,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Magnesium",
                        amount: 56.7,
                        unit: "mg",
                        percentOfDailyNeeds: 25.63,
                    },
                    {
                        name: "Vitamin B12",
                        amount: 5.41,
                        unit: "µg",
                        percentOfDailyNeeds: 91.79,
                    },
                    {
                        name: "Cholesterol",
                        amount: 113.4,
                        unit: "mg",
                        percentOfDailyNeeds: 37.8,
                    },
                    {
                        name: "Poly Unsaturated Fat",
                        amount: 1.11,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Folic Acid",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B6",
                        amount: 0.43,
                        unit: "mg",
                        percentOfDailyNeeds: 32.06,
                    },
                    {
                        name: "Vitamin B1",
                        amount: 0.14,
                        unit: "mg",
                        percentOfDailyNeeds: 12.49,
                    },
                    {
                        name: "Vitamin B2",
                        amount: 0.04,
                        unit: "mg",
                        percentOfDailyNeeds: 5.03,
                    },
                    {
                        name: "Selenium",
                        amount: 51.74,
                        unit: "µg",
                        percentOfDailyNeeds: 77.87,
                    },
                    {
                        name: "Net Carbohydrates",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 6.76,
                    },
                    {
                        name: "Calcium",
                        amount: 21.26,
                        unit: "mg",
                        percentOfDailyNeeds: 5.38,
                    },
                    {
                        name: "Zinc",
                        amount: 0.57,
                        unit: "mg",
                        percentOfDailyNeeds: 5.21,
                    },
                    {
                        name: "Vitamin A",
                        amount: 127.57,
                        unit: "IU",
                        percentOfDailyNeeds: 6.36,
                    },
                    {
                        name: "Iron",
                        amount: 1.19,
                        unit: "mg",
                        percentOfDailyNeeds: 9.33,
                    },
                    {
                        name: "Fiber",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 2.7,
                    },
                    {
                        name: "Saturated Fat",
                        amount: 0.72,
                        unit: "g",
                        percentOfDailyNeeds: 12.67,
                    },
                    {
                        name: "Protein",
                        amount: 25.13,
                        unit: "g",
                        percentOfDailyNeeds: 54.2,
                    },
                    {
                        name: "Alcohol",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 100.0,
                    },
                    {
                        name: "Vitamin C",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 68.48,
                    },
                    {
                        name: "Vitamin B5",
                        amount: 1.06,
                        unit: "mg",
                        percentOfDailyNeeds: 12.31,
                    },
                    {
                        name: "Fat",
                        amount: 3.3,
                        unit: "g",
                        percentOfDailyNeeds: 19.3,
                    },
                    {
                        name: "Phosphorus",
                        amount: 280.66,
                        unit: "mg",
                        percentOfDailyNeeds: 30.85,
                    },
                    {
                        name: "Folate",
                        amount: 12.76,
                        unit: "µg",
                        percentOfDailyNeeds: 8.5,
                    },
                    {
                        name: "Copper",
                        amount: 0.04,
                        unit: "mg",
                        percentOfDailyNeeds: 6.0,
                    },
                    {
                        name: "Vitamin B3",
                        amount: 2.98,
                        unit: "mg",
                        percentOfDailyNeeds: 18.57,
                    },
                    {
                        name: "Sodium",
                        amount: 97.81,
                        unit: "mg",
                        percentOfDailyNeeds: 70.4,
                    },
                ],
            },
            {
                id: 4058,
                name: "sesame oil",
                amount: 0.04,
                unit: "cup",
                nutrients: [
                    {
                        name: "Potassium",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 16.8,
                    },
                    {
                        name: "Carbohydrates",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 6.42,
                    },
                    {
                        name: "Calories",
                        amount: 80.3,
                        unit: "kcal",
                        percentOfDailyNeeds: 14.61,
                    },
                    {
                        name: "Mono Unsaturated Fat",
                        amount: 3.61,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B12",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 91.79,
                    },
                    {
                        name: "Magnesium",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 25.63,
                    },
                    {
                        name: "Cholesterol",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 37.8,
                    },
                    {
                        name: "Vitamin E",
                        amount: 0.13,
                        unit: "mg",
                        percentOfDailyNeeds: 2.68,
                    },
                    {
                        name: "Poly Unsaturated Fat",
                        amount: 3.79,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Folic Acid",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B6",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 32.06,
                    },
                    {
                        name: "Vitamin B1",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 12.49,
                    },
                    {
                        name: "Vitamin B2",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 5.03,
                    },
                    {
                        name: "Selenium",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 77.87,
                    },
                    {
                        name: "Net Carbohydrates",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 6.76,
                    },
                    {
                        name: "Choline",
                        amount: 0.02,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Calcium",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 5.38,
                    },
                    {
                        name: "Vitamin D",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Zinc",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 5.21,
                    },
                    {
                        name: "Vitamin A",
                        amount: 0.0,
                        unit: "IU",
                        percentOfDailyNeeds: 6.36,
                    },
                    {
                        name: "Caffeine",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Iron",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 9.33,
                    },
                    {
                        name: "Fiber",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 2.7,
                    },
                    {
                        name: "Saturated Fat",
                        amount: 1.29,
                        unit: "g",
                        percentOfDailyNeeds: 12.67,
                    },
                    {
                        name: "Vitamin B5",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 12.31,
                    },
                    {
                        name: "Protein",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 54.2,
                    },
                    {
                        name: "Alcohol",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 100.0,
                    },
                    {
                        name: "Lycopene",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin C",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 68.48,
                    },
                    {
                        name: "Sugar",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 12.35,
                    },
                    {
                        name: "Fat",
                        amount: 9.08,
                        unit: "g",
                        percentOfDailyNeeds: 19.3,
                    },
                    {
                        name: "Phosphorus",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 30.85,
                    },
                    {
                        name: "Folate",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 8.5,
                    },
                    {
                        name: "Copper",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 6.0,
                    },
                    {
                        name: "Vitamin B3",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 18.57,
                    },
                    {
                        name: "Vitamin K",
                        amount: 1.24,
                        unit: "µg",
                        percentOfDailyNeeds: 3.43,
                    },
                    {
                        name: "Sodium",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 70.4,
                    },
                ],
            },
            {
                id: 19335,
                name: "sugar",
                amount: 0.04,
                unit: "cup",
                nutrients: [
                    {
                        name: "Potassium",
                        amount: 0.17,
                        unit: "mg",
                        percentOfDailyNeeds: 16.8,
                    },
                    {
                        name: "Manganese",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 10.54,
                    },
                    {
                        name: "Carbohydrates",
                        amount: 8.3,
                        unit: "g",
                        percentOfDailyNeeds: 6.42,
                    },
                    {
                        name: "Calories",
                        amount: 32.08,
                        unit: "kcal",
                        percentOfDailyNeeds: 14.61,
                    },
                    {
                        name: "Mono Unsaturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B12",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 91.79,
                    },
                    {
                        name: "Magnesium",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 25.63,
                    },
                    {
                        name: "Cholesterol",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 37.8,
                    },
                    {
                        name: "Vitamin E",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 2.68,
                    },
                    {
                        name: "Poly Unsaturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Folic Acid",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B6",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 32.06,
                    },
                    {
                        name: "Vitamin B1",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 12.49,
                    },
                    {
                        name: "Vitamin B2",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 5.03,
                    },
                    {
                        name: "Selenium",
                        amount: 0.05,
                        unit: "µg",
                        percentOfDailyNeeds: 77.87,
                    },
                    {
                        name: "Net Carbohydrates",
                        amount: 8.3,
                        unit: "g",
                        percentOfDailyNeeds: 6.76,
                    },
                    {
                        name: "Choline",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Calcium",
                        amount: 0.08,
                        unit: "mg",
                        percentOfDailyNeeds: 5.38,
                    },
                    {
                        name: "Vitamin D",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Zinc",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 5.21,
                    },
                    {
                        name: "Vitamin A",
                        amount: 0.0,
                        unit: "IU",
                        percentOfDailyNeeds: 6.36,
                    },
                    {
                        name: "Caffeine",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Iron",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 9.33,
                    },
                    {
                        name: "Fiber",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 2.7,
                    },
                    {
                        name: "Saturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 12.67,
                    },
                    {
                        name: "Vitamin B5",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 12.31,
                    },
                    {
                        name: "Protein",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 54.2,
                    },
                    {
                        name: "Alcohol",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 100.0,
                    },
                    {
                        name: "Lycopene",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin C",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 68.48,
                    },
                    {
                        name: "Fluoride",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Sugar",
                        amount: 8.32,
                        unit: "g",
                        percentOfDailyNeeds: 12.35,
                    },
                    {
                        name: "Fat",
                        amount: 0.03,
                        unit: "g",
                        percentOfDailyNeeds: 19.3,
                    },
                    {
                        name: "Phosphorus",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 30.85,
                    },
                    {
                        name: "Folate",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 8.5,
                    },
                    {
                        name: "Vitamin B3",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 18.57,
                    },
                    {
                        name: "Copper",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 6.0,
                    },
                    {
                        name: "Vitamin K",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 3.43,
                    },
                    {
                        name: "Sodium",
                        amount: 0.08,
                        unit: "mg",
                        percentOfDailyNeeds: 70.4,
                    },
                ],
            },
            {
                id: 11670,
                name: "thai bird chiles",
                amount: 0.08,
                unit: "cup",
                nutrients: [
                    {
                        name: "Potassium",
                        amount: 42.5,
                        unit: "mg",
                        percentOfDailyNeeds: 16.8,
                    },
                    {
                        name: "Manganese",
                        amount: 0.03,
                        unit: "mg",
                        percentOfDailyNeeds: 10.54,
                    },
                    {
                        name: "Carbohydrates",
                        amount: 1.18,
                        unit: "g",
                        percentOfDailyNeeds: 6.42,
                    },
                    {
                        name: "Calories",
                        amount: 5.0,
                        unit: "kcal",
                        percentOfDailyNeeds: 14.61,
                    },
                    {
                        name: "Mono Unsaturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B12",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 91.79,
                    },
                    {
                        name: "Magnesium",
                        amount: 3.13,
                        unit: "mg",
                        percentOfDailyNeeds: 25.63,
                    },
                    {
                        name: "Cholesterol",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 37.8,
                    },
                    {
                        name: "Vitamin E",
                        amount: 0.09,
                        unit: "mg",
                        percentOfDailyNeeds: 2.68,
                    },
                    {
                        name: "Poly Unsaturated Fat",
                        amount: 0.01,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Folic Acid",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B6",
                        amount: 0.03,
                        unit: "mg",
                        percentOfDailyNeeds: 32.06,
                    },
                    {
                        name: "Vitamin B1",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 12.49,
                    },
                    {
                        name: "Vitamin B2",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 5.03,
                    },
                    {
                        name: "Selenium",
                        amount: 0.06,
                        unit: "µg",
                        percentOfDailyNeeds: 77.87,
                    },
                    {
                        name: "Net Carbohydrates",
                        amount: 0.99,
                        unit: "g",
                        percentOfDailyNeeds: 6.76,
                    },
                    {
                        name: "Choline",
                        amount: 1.39,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Calcium",
                        amount: 2.25,
                        unit: "mg",
                        percentOfDailyNeeds: 5.38,
                    },
                    {
                        name: "Vitamin D",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Zinc",
                        amount: 0.04,
                        unit: "mg",
                        percentOfDailyNeeds: 5.21,
                    },
                    {
                        name: "Vitamin A",
                        amount: 147.38,
                        unit: "IU",
                        percentOfDailyNeeds: 6.36,
                    },
                    {
                        name: "Caffeine",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Iron",
                        amount: 0.15,
                        unit: "mg",
                        percentOfDailyNeeds: 9.33,
                    },
                    {
                        name: "Fiber",
                        amount: 0.19,
                        unit: "g",
                        percentOfDailyNeeds: 2.7,
                    },
                    {
                        name: "Saturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 12.67,
                    },
                    {
                        name: "Vitamin B5",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 12.31,
                    },
                    {
                        name: "Protein",
                        amount: 0.25,
                        unit: "g",
                        percentOfDailyNeeds: 54.2,
                    },
                    {
                        name: "Alcohol",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 100.0,
                    },
                    {
                        name: "Lycopene",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin C",
                        amount: 30.31,
                        unit: "mg",
                        percentOfDailyNeeds: 68.48,
                    },
                    {
                        name: "Sugar",
                        amount: 0.64,
                        unit: "g",
                        percentOfDailyNeeds: 12.35,
                    },
                    {
                        name: "Fat",
                        amount: 0.03,
                        unit: "g",
                        percentOfDailyNeeds: 19.3,
                    },
                    {
                        name: "Phosphorus",
                        amount: 5.75,
                        unit: "mg",
                        percentOfDailyNeeds: 30.85,
                    },
                    {
                        name: "Folate",
                        amount: 2.88,
                        unit: "µg",
                        percentOfDailyNeeds: 8.5,
                    },
                    {
                        name: "Vitamin B3",
                        amount: 0.12,
                        unit: "mg",
                        percentOfDailyNeeds: 18.57,
                    },
                    {
                        name: "Copper",
                        amount: 0.02,
                        unit: "mg",
                        percentOfDailyNeeds: 6.0,
                    },
                    {
                        name: "Vitamin K",
                        amount: 1.79,
                        unit: "µg",
                        percentOfDailyNeeds: 3.43,
                    },
                    {
                        name: "Sodium",
                        amount: 0.88,
                        unit: "mg",
                        percentOfDailyNeeds: 70.4,
                    },
                ],
            },
            {
                id: 1006179,
                name: "thai fish sauce",
                amount: 0.08,
                unit: "cup",
                nutrients: [
                    {
                        name: "Potassium",
                        amount: 55.68,
                        unit: "mg",
                        percentOfDailyNeeds: 16.8,
                    },
                    {
                        name: "Manganese",
                        amount: 0.05,
                        unit: "mg",
                        percentOfDailyNeeds: 10.54,
                    },
                    {
                        name: "Carbohydrates",
                        amount: 0.7,
                        unit: "g",
                        percentOfDailyNeeds: 6.42,
                    },
                    {
                        name: "Calories",
                        amount: 6.77,
                        unit: "kcal",
                        percentOfDailyNeeds: 14.61,
                    },
                    {
                        name: "Mono Unsaturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B12",
                        amount: 0.09,
                        unit: "µg",
                        percentOfDailyNeeds: 91.79,
                    },
                    {
                        name: "Magnesium",
                        amount: 33.83,
                        unit: "mg",
                        percentOfDailyNeeds: 25.63,
                    },
                    {
                        name: "Cholesterol",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 37.8,
                    },
                    {
                        name: "Vitamin E",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 2.68,
                    },
                    {
                        name: "Poly Unsaturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Folic Acid",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin B6",
                        amount: 0.08,
                        unit: "mg",
                        percentOfDailyNeeds: 32.06,
                    },
                    {
                        name: "Vitamin B1",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 12.49,
                    },
                    {
                        name: "Vitamin B2",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 5.03,
                    },
                    {
                        name: "Selenium",
                        amount: 1.76,
                        unit: "µg",
                        percentOfDailyNeeds: 77.87,
                    },
                    {
                        name: "Net Carbohydrates",
                        amount: 0.7,
                        unit: "g",
                        percentOfDailyNeeds: 6.76,
                    },
                    {
                        name: "Choline",
                        amount: 2.55,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Calcium",
                        amount: 8.31,
                        unit: "mg",
                        percentOfDailyNeeds: 5.38,
                    },
                    {
                        name: "Vitamin D",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Zinc",
                        amount: 0.04,
                        unit: "mg",
                        percentOfDailyNeeds: 5.21,
                    },
                    {
                        name: "Vitamin A",
                        amount: 2.32,
                        unit: "IU",
                        percentOfDailyNeeds: 6.36,
                    },
                    {
                        name: "Caffeine",
                        amount: 0.0,
                        unit: "mg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Iron",
                        amount: 0.15,
                        unit: "mg",
                        percentOfDailyNeeds: 9.33,
                    },
                    {
                        name: "Fiber",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 2.7,
                    },
                    {
                        name: "Saturated Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 12.67,
                    },
                    {
                        name: "Vitamin B5",
                        amount: 0.02,
                        unit: "mg",
                        percentOfDailyNeeds: 12.31,
                    },
                    {
                        name: "Protein",
                        amount: 0.98,
                        unit: "g",
                        percentOfDailyNeeds: 54.2,
                    },
                    {
                        name: "Alcohol",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 100.0,
                    },
                    {
                        name: "Lycopene",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 0.0,
                    },
                    {
                        name: "Vitamin C",
                        amount: 0.1,
                        unit: "mg",
                        percentOfDailyNeeds: 68.48,
                    },
                    {
                        name: "Sugar",
                        amount: 0.7,
                        unit: "g",
                        percentOfDailyNeeds: 12.35,
                    },
                    {
                        name: "Fat",
                        amount: 0.0,
                        unit: "g",
                        percentOfDailyNeeds: 19.3,
                    },
                    {
                        name: "Phosphorus",
                        amount: 1.35,
                        unit: "mg",
                        percentOfDailyNeeds: 30.85,
                    },
                    {
                        name: "Folate",
                        amount: 9.86,
                        unit: "µg",
                        percentOfDailyNeeds: 8.5,
                    },
                    {
                        name: "Vitamin B3",
                        amount: 0.45,
                        unit: "mg",
                        percentOfDailyNeeds: 18.57,
                    },
                    {
                        name: "Copper",
                        amount: 0.01,
                        unit: "mg",
                        percentOfDailyNeeds: 6.0,
                    },
                    {
                        name: "Vitamin K",
                        amount: 0.0,
                        unit: "µg",
                        percentOfDailyNeeds: 3.43,
                    },
                    {
                        name: "Sodium",
                        amount: 1517.67,
                        unit: "mg",
                        percentOfDailyNeeds: 70.4,
                    },
                ],
            },
        ],
        caloricBreakdown: {
            percentProtein: 36.33,
            percentFat: 37.83,
            percentCarbs: 25.84,
        },
        weightPerServing: {
            amount: 280,
            unit: "g",
        },
    },
    summary:
        'Need a <b>gluten free, dairy free, and pescatarian main course</b>? Grilled Sea Bass with Thai Chili Sauce could be an outstanding recipe to try. One portion of this dish contains about <b>52g of protein</b>, <b>16g of fat</b>, and a total of <b>430 calories</b>. For <b>$4.96 per serving</b>, this recipe <b>covers 20%</b> of your daily requirements of vitamins and minerals. This recipe serves 6. This recipe from Foodnetwork requires sea bass fillets, sugar, thai bird chiles, and sesame oil. It is a <b>rather expensive</b> recipe for fans of American food. 1 person were glad they tried this recipe. From preparation to the plate, this recipe takes around <b>1 hour and 25 minutes</b>. <b>The Fourth Of July</b> will be even more special with this recipe. Overall, this recipe earns a <b>solid spoonacular score of 69%</b>. Similar recipes are <a href="https://spoonacular.com/recipes/stuffed-giant-sea-shells-or-manicotti-42312">Stuffed Giant Sea Shells Or Manicotti</a>, <a href="https://spoonacular.com/recipes/roasted-sea-bream-with-anchoiade-658661">Roasted Sea Bream With Anchoiade</a>, and <a href="https://spoonacular.com/recipes/sea-salted-caramels-659621">Sea Salted Caramels</a>.',
    cuisines: ["American"],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "pescatarian"],
    occasions: ["super bowl", "father's day", "4th of july", "summer"],
    instructions:
        "In medium bowl mix lime juice, fish sauce, garlic, chiles, ginger, sesame oil and sugar. Pour half of the sauce over the fish and let sit for 1 hour refrigerated. Discard the marinade used for the fish. Grill fish over high heat, about 5 to 7 minutes, or until cooked through, and serve with the remaining half of the sauce.",
    analyzedInstructions: [
        {
            name: "",
            steps: [
                {
                    number: 1,
                    step: "In medium bowl mix lime juice, fish sauce, garlic, chiles, ginger, sesame oil and sugar.",
                    ingredients: [
                        {
                            id: 6179,
                            name: "fish sauce",
                            localizedName: "fish sauce",
                            image: "asian-fish-sauce.jpg",
                        },
                        {
                            id: 9160,
                            name: "lime juice",
                            localizedName: "lime juice",
                            image: "lime-juice.png",
                        },
                        {
                            id: 4058,
                            name: "sesame oil",
                            localizedName: "sesame oil",
                            image: "sesame-oil.png",
                        },
                        {
                            id: 11819,
                            name: "chili pepper",
                            localizedName: "chili pepper",
                            image: "red-chili.jpg",
                        },
                        {
                            id: 11215,
                            name: "garlic",
                            localizedName: "garlic",
                            image: "garlic.png",
                        },
                        {
                            id: 11216,
                            name: "ginger",
                            localizedName: "ginger",
                            image: "ginger.png",
                        },
                        {
                            id: 19335,
                            name: "sugar",
                            localizedName: "sugar",
                            image: "sugar-in-bowl.png",
                        },
                    ],
                    equipment: [
                        {
                            id: 404783,
                            name: "bowl",
                            localizedName: "bowl",
                            image: "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
                        },
                    ],
                },
                {
                    number: 2,
                    step: "Pour half of the sauce over the fish and let sit for 1 hour refrigerated. Discard the marinade used for the fish. Grill fish over high heat, about 5 to 7 minutes, or until cooked through, and serve with the remaining half of the sauce.",
                    ingredients: [
                        {
                            id: 0,
                            name: "marinade",
                            localizedName: "marinade",
                            image: "seasoning.png",
                        },
                        {
                            id: 0,
                            name: "sauce",
                            localizedName: "sauce",
                            image: "",
                        },
                        {
                            id: 10115261,
                            name: "fish",
                            localizedName: "fish",
                            image: "fish-fillet.jpg",
                        },
                    ],
                    equipment: [
                        {
                            id: 404706,
                            name: "grill",
                            localizedName: "grill",
                            image: "https://spoonacular.com/cdn/equipment_100x100/grill.jpg",
                        },
                    ],
                    length: {
                        number: 65,
                        unit: "minutes",
                    },
                },
            ],
        },
    ],
    originalId: null,
    spoonacularScore: 68.7918930053711,
};
const Detail = () => {
    const { id } = useLocalSearchParams();
    return (
        <ScrollView>
            <Image source={gambar} style={styles.image} />
            <View style={styles.container}>
                <View style={styles.titleContainer}>
                    <Text style={styles.title}>{data.title}</Text>
                    <Pressable>
                        <AntDesign name="heart" size={24} color="red" />
                    </Pressable>
                </View>
            </View>
            <View style={styles.contentContainer}>
                <FlatList
                    scrollEnabled={false}
                    data={data.nutrition.nutrients}
                    renderItem={({ item }) => (
                        <Text>
                            {item.name}: {item.amount} {item.unit}
                        </Text>
                    )}
                />
                <FlatList
                    scrollEnabled={false}
                    data={data.analyzedInstructions[0].steps}
                    renderItem={({ item, index }) => (
                        <Text>
                            {index + 1}. {item.step}
                        </Text>
                    )}
                />
            </View>
            {/* <Text>Detail</Text> */}
        </ScrollView>
    );
};

const styles = StyleSheet.create({
    container: {
        backgroundColor: "#fff",
        marginTop: -20,

        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingTop: 20,
        paddingHorizontal: 20,
    },
    image: {
        width: "100%",
        height: 400,
        objectFit: "cover",
        backgroundColor: "#2278ed",
    },
    titleContainer: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingRight: 10,
        marginBottom: 40,
    },
    title: {
        width: 300,
        fontSize: 20,
        fontWeight: "bold",
    },
    contentContainer: {
        width: "100%",
        paddingHorizontal: 20,
        backgroundColor: "#fff",
    },
});

export default Detail;
